### ISSUE TITLE
Add option to prefix filename with created_time 

### ISSUE THREAD

**Issue by Claybro** [rarcega/instagram-scraper#1]
Accidentally hit the enter button on my phone and submitted with half a title and no description, my bad. 

Anyways, I wanted to know if you could add a feature to append the date the image was uploaded to Instagram to the beginning of the file name. I'm trying to download all my pictures but don't want the random file names that Instagram assigns. I made a few additions myself, but my Python skills are next to nonexistent so I got stuck at that part.

**Comment by rarcega** [comment]
Usage:

```bash
python app.py --prefix-created-time="%Y%m%dT%H%M%S_" username
```

**Comment by devkhan** [comment]
@rarcega Is this option removed? I can't get it to work:

`instagram-scraper: error: unrecognized arguments: --prefix-created-time=%Y%m%dT%H%M%S_`
