### ISSUE TITLE
FR: Only gather media till overlaps most recent existing file

### ISSUE THREAD

**Issue by CNG** [rarcega/instagram-scraper#10]
_Note: The following is a theoretical exercise and I am not advocating this be used in violation of any terms of service or law._

This is similar to [#8](https://github.com/rarcega/instagram-scraper/issues/8) but more complicated to implement. Not downloading existing files is a huge improvement, but it still takes a lot of time to download all the media information and then check if the files exist.

I don't use Instagram myself, but I am guessing users cannot retroactively add media? If that's true, the script should be able to check the date of the newest file in the folder that would be created upon first run and then only collect the media info till that date is reached. If this script is being run daily, for instance, likely it would never need to pull more than the first batch of photos. Such a daily update would then be feasible to run on a large number of accounts with a large number of photos.

I'd think that could again be implemented as default behavior and not require an option, unless the script were later augmented to check if any files were previously saved but no longer appear in the Instagram account, as a sort of "deletion detection" feature.

**Comment by Skinner927** [comment]
I've made something that does that. I would have extended `instagram-scraper`, but I yanked a bunch of this code out of another project I was working on which used parts of `instagram-scraper`, maybe one day.

https://github.com/Skinner927/instagram-scrape-and-mail

**Comment by rarcega** [comment]
Added --latest argument which will only new media since the last scrape. Uses the last modified time of the latest media item in the destination directory to compare.

**Comment by CNG** [comment]
This works wonderfully. THANK YOU!!

**Comment by TheCelavi** [comment]
Does this works for type=story as well?
