### ISSUE TITLE
How to only get the JSON file and not any of the images?

### ISSUE THREAD

**Issue by raghunayyar** [rarcega/instagram-scraper#107]
I need to scrape of user data as per hashtag, I don't need the images and I only need the JSON file generated in the end? Is it possible?

**Comment by Filooou** [comment]
Hey, have you tried the following:
instagram-scraper <username> --media_metadata --media_types none

**Comment by raghunayyar** [comment]
Perfect, thanks.

**Comment by ktktech** [comment]
Hello, 
I tried doing this way but when I access the folder, its blank. no files :(
