### ISSUE TITLE
User does not exist

### ISSUE THREAD

**Issue by RaviGill247** [rarcega/instagram-scraper#118]
Whenever trying to run the scraper, I get a "user does not exist" error. Even though the user exists and has a public profile.

**Comment by mikeydiamonds** [comment]
I'm getting the same but it worked perfectly 2 days ago

**Comment by mikeydiamonds** [comment]
It must have something to do with https://github.com/rarcega/instagram-scraper/issues/117

**Comment by zacjor** [comment]
I tried a different instagram scrapper and I was having the same issues. Maybe there has been a change to instragram.com?

**Comment by myoniles** [comment]
I am getting this issue as well

**Comment by mikeydiamonds** [comment]
Instagram changed the api by removing the media endpoint

**Comment by mikeydiamonds** [comment]
the scraper was using https://www.instagram.com/$user/media to get all the media but if you put your username in place of '$user' the page is not found

**Comment by rarcega** [comment]
Fixed in v1.5.7

To upgrade: pip install instagram-scraper --upgrade

**Comment by VasiliPupkin256** [comment]
It is now fail to recognize private closed profiles and doesn't show error in a log

**Comment by ashvar** [comment]
Still doesn't work with 1.5.13.

**Comment by jahidmixmaster** [comment]
I am getting also the same error. It worked perfectly until 15.09.2019
