### ISSUE TITLE
FR: Useful error message for nonexistent accounts

### ISSUE THREAD

**Issue by CNG** [rarcega/instagram-scraper#12]
Currently when attempting to scrape a nonexistent account, there is an ugly error message that doesn't even include the name of the account, which is unhelpful when reviewing a cron log.

Example:

> Traceback (most recent call last):
>   File "/Volumes/Minerva/Software/instagram-scraper/app.py", line 82, in <module>
>     scraper.crawl()
>   File "/Volumes/Minerva/Software/instagram-scraper/app.py", line 35, in crawl
>     media = json.loads(resp.text)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded

**Comment by rarcega** [comment]
The following error raised when this occurs and the script exits with an exit code of 1.

`ValueError: User moonootcy does not exist`
