### ISSUE TITLE
FR: Support private accounts

### ISSUE THREAD

**Issue by CNG** [rarcega/instagram-scraper#13]
I assume this was considered but not required by the original author and thus not mentioned, but it seems obvious enough to warrant documenting as a request even if just to acknowledge it was investigated and won't be possible. Any details would be appreciated in case someone wants to take a crack at it, but I don't have an immediate need for this.

What's the current status?
1. Not yet researched.
2. Some research but not yet known if possible.
3. Researched; possible but not implemented.
4. Researched; not possible.

**Comment by Rich700000000000** [comment]
This.. Would be really hard to implement. In order to access the images on a private account, you first need to have an Instagram account and be given access by that person. It would require multiple levels of login threading, and slow the script down immensely.

**Comment by CNG** [comment]
I know those would be prerequisites, but a slow script is better than no solution. Anyway, just curious what else would be involved if known. Thanks!

**Comment by rarcega** [comment]
I can see why this would desirable. Have not researched it yet. I'll provide an update whenever I get to it, but don't hold your breath :)

**Comment by rarcega** [comment]
@CNG @Rich700000000000 

To scrape a private user's media when you are an approved follower:

`$ python app.py <username> -u <your username> -p <your password>`

**Comment by CNG** [comment]
I will have a look this weekend. Thank you!!

**Comment by CNG** [comment]
Had some delays due to escaping special characters in my password in a cron job… anyway, the script worked when I tested on one user account, but in my automated flow, it fails to log in. I only had time for a quick look, where I output response.text and got:

> {"status": "fail", "message": "Sorry, too many requests. Please try again later."}

Once the script runs into that issue (after going through a number of accounts to scrape, most of which are public), if I stop the script and restart it, I get the error immediately. It looks like this is because it tries to log in upon instantiation. (Maybe it shouldn't log in until required?)

Let me know if I should provide more info or if this is enough to go on. 

Thanks!

**Comment by rarcega** [comment]
Thanks @CNG for the feedback. I encountered the same error while adding support for scraping  [user stories](http://blog.instagram.com/post/148348940287/160802-stories) which also requires a login.

It does appear that there is a cap on the number of logins you can make over a period of time even if you log out. I'll need to perform more testing to determine the precise conditions. Logic can be added to login only if the account is private, however under the type of workflow you describe, the issue can still potentially manifest if a large number of private accounts are scraped. In that case, it makes sense to login once and maintain the same session throughout. This will necessitate the ability to accept a list of users as input to the script. I'll look into it and keep you posted.

**Comment by rarcega** [comment]
I've made modifications to support passing in a list of usernames either via command-line or a file.

To specify multiple users, pass a delimited list of users:
```bash
$ instagram-scraper username1,username2,username3           
```

You can also supply a file containing a list of usernames:
```bash
$ instagram-scraper -f ig_users.txt           
```
The usernames may be delimited by newlines, commas, semicolons, or whitespace.

**Comment by CNG** [comment]
Again, thank you for the quick update. I'm going to need to reorganize before testing again, as I had previously been crawling a directory structure and `cd`ing to certain directories before running the script. It would actually work better for me to get all the folders in a central location, though. I'll have some time for this in about 10 days.

**Comment by CNG** [comment]
Thank you again for this update! I tested it successfully, after centralizing my directories, which was worth the effort in itself.

BTW, when I said I would get to it in 10 days, I obviously intended to say 107.
