### ISSUE TITLE
Login failed 

### ISSUE THREAD

**Issue by merihach** [rarcega/instagram-scraper#151]
<img width="923" alt="screen shot 1396-10-14 at 23 16 08" src="https://user-images.githubusercontent.com/30000269/34581866-3d332dee-f1a7-11e7-9694-284f18c067f0.png">
instagram-scraper worked properly for several times but today login failed.

**Comment by gvkalra** [comment]
@merihach try the interactive mode:
```
--interactive -i    Enables interactive login challenge solving. Has 2 modes: SMS and Email
```
