### ISSUE TITLE
Instagram start to block full resolution image URLs

### ISSUE THREAD

**Issue by VasiliPupkin256** [rarcega/instagram-scraper#157]
It is caused by this function
https://github.com/rarcega/instagram-scraper/blob/9ddf15a8e7e9351493721fc4b8cf9b12fda9522e/instagram_scraper/app.py#L653-L659
I didn't find the pattern. Some images, very rare, are blocked if you strip resolution part from its url. For example: https://www.instagram.com/p/BS1colrjDMO/ its image address is https://scontent-arn2-1.cdninstagram.com/vp/fff7bcde3152b4beb197df8876cb4813/5ADC4B70/t51.2885-15/s1080x1080/e35/17495064_1315799695124197_1952724911399108608_n.jpg the middle part s1080x1080 is removed by this function and the resulted url https://scontent-arn2-1.cdninstagram.com/vp/fff7bcde3152b4beb197df8876cb4813/5ADC4B70/t51.2885-15/e35/17495064_1315799695124197_1952724911399108608_n.jpg is blocked by instagram

**Comment by gvkalra** [comment]
Am also noticing this...

**Comment by Trixpua** [comment]
I think, it can be changed, to get by default with s1080x1080, that is the max resolution possible in instagram.

**Comment by VasiliPupkin256** [comment]
The issue start to affect more and more images. I'm getting it rather regularly now. Still don't see the pattern

**Comment by VasiliPupkin256** [comment]
It looks like most parts of the url can be stripped starting from the `/vp/`, and the `/e35/` can be stripped as well, still wonder what it is
So here is the original resolution image url https://scontent-arn2-1.cdninstagram.com/t51.2885-15/17495064_1315799695124197_1952724911399108608_n.jpg
And it is bigger than 1080x1080, @Trixpua

**Comment by VasiliPupkin256** [comment]
The hack is not working anymore. It now returns "Bad URL date param" or "Access Denied" for shortened urls.
