### ISSUE TITLE
Script acts erratically on raspi. 

### ISSUE THREAD

**Issue by Rich700000000000** [rarcega/instagram-scraper#16]
I have a raspberry pi, and so I made a few modifications to the script so I can run it as a scraping server:

```
    def downacc(username):
        scraper = InstagramScraper(username)
        scraper.crawl()

        for future in tqdm.tqdm(concurrent.futures.as_completed(scraper.future_to_item), total=len(scraper.future_to_item), desc='Downloading'):
        item = scraper.future_to_item[future]

        if future.exception() is not None:
            print('%r generated an exception: %s') % (item['id'], future.exception())


    def getAccounts():
        with open('./ig.txt') as f:
            lines = f.read().splitlines()
        return lines


    def main():
        accs = getAccounts()
        for i in accs:
            downacc(i)


    main()
```

It reads a list of usernames from a txt file. However, despite making only minor changes, the script is completely broken: It freezes, crashes, stalls, and gives random erratic errors. What could be the cause of this?

**Comment by rarcega** [comment]
This is difficult for me to troubleshoot since I can't replicate the Raspberry Pi environment. Does this happen with the unmodified script?

**Comment by Rich700000000000** [comment]
Actually, no. That's running with no problems. Weird.

**Comment by rarcega** [comment]
If you have bash shell with GNU parallel available the following will work:

`cat ig.txt | parallel -j5 "python app.py {}"`
