### ISSUE TITLE
How do you use this as a Cronjob

### ISSUE THREAD

**Issue by mikeyside** [rarcega/instagram-scraper#180]
I would like to run this as a cronjob but am having no luck. Any ideas?

**Comment by gbaxiom** [comment]
You need to reference the binary directly in your cron.

So instead of "instagram-scraper <ARGS>" do "/usr/bin/instagram-scraper <ARGS>" or wherever your binary is located at.

**Comment by vanyasem** [comment]
Consider closing the issue, it has nothing to do with `instagram-scraper`
