### ISSUE TITLE
Can't scrape user stories

### ISSUE THREAD

**Issue by clublek** [rarcega/instagram-scraper#183]
Using command:

instagram-scraper -u {USERNAME} -p {PASSWORD} -f C:\Stories\igusers.txt -d C:\Stories -n -t story --latest --interactive

Output:

Traceback (most recent call last):
  File "C:\Python361\Scripts\instagram-scraper-script.py", line 11, in <module>
    load_entry_point('instagram-scraper==1.5.20', 'console_scripts', 'instagram-scraper')()
  File "c:\python361\lib\site-packages\instagram_scraper\app.py", line 1077, in main
    scraper.scrape()
  File "c:\python361\lib\site-packages\instagram_scraper\app.py", line 558, in scrape
    user = self.get_user(username)
  File "c:\python361\lib\site-packages\instagram_scraper\app.py", line 630, in get_user
    user = json.loads(resp)['user']
KeyError: 'user'

**Comment by firstneithernorlast** [comment]
I'm getting the same error. Please post the solution if you find one.

**Comment by shyd** [comment]
Look at PR #182 

I just gave it a test shot with my docker image with the `dev` tag: https://hub.docker.com/r/shyd/instagram-scraper/

This error is now gone, but `KeyError: 'media'` comes along.

**Comment by Pepsilake** [comment]
By changing line 630 is it now possible to scrape images and videos but not stories.
It doesn't return anything, if there was no folder then it's created but it's empty.
How do you solve that?

**Comment by rarcega** [comment]
Please upgrade to v1.5.23

`pip install instagram-scraper --upgrade`
