### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by richtercamden** [rarcega/instagram-scraper#184]
About a week ago, everything was working perfectly. Today, I start it after having not run it for a week, and now I'm getting this error (KeyError: 'user'). I've tried different inputs and I've tried reinstalling with pip. Nothing I can think of has fixed it. Help would be very appreciated!

**Comment by rarcega** [comment]
Please upgrade to v1.5.23

`pip install instagram-scraper --upgrade`

**Comment by shyd** [comment]
@rarcega Thanks for the quick response with fixes! 👍
