### ISSUE TITLE
Challenge in interactive mode does not work

### ISSUE THREAD

**Issue by TheCelavi** [rarcega/instagram-scraper#186]
When account is flagged, it is impossible to verify it in interactive mode: 

ERROR: Please verify your account at /challenge/183432073/Cv8o3kmUOG/

Choose a challenge mode (0 - SMS, 1 - Email): 1

Whatever is chosen, nothing is sent from Instagram. This used to work, yesterday we know that Instagram changed format of its responses and so on... 

We believe that update is required for this functionality to work again.

Until that, this functionality is broken.

**Comment by TheCelavi** [comment]
Seams that it is impossible to login at all, tried different accounts, all real ones. 

What about headers that are sent? Seams that Instagram seams those as Windows NT or whatever... is it possible to setup headers for client?

**Comment by TheCelavi** [comment]
False positive - something is wrong with my environment.

**Comment by lameira** [comment]
I have the same issue. What was wrong with you environment?

**Comment by TheCelavi** [comment]
Hello, sorry, I am ill so not working for few days now... We kinda dropped usage of scraper, so I have stopped to work on debugging, sorry. I don't have any useful info for you.

**Comment by VasiliPupkin256** [comment]
@TheCelavi do you mean you dropped usage of instagram or there is a tool that overcome the issue?

**Comment by TheCelavi** [comment]
We are going to try to use FB graph api for Instsa business accounts - that could help us a lot.
