### ISSUE TITLE
Stopped working with option:  "--media-types none"

### ISSUE THREAD

**Issue by arnaudmarchal** [rarcega/instagram-scraper#189]
I used to run :
instagram-scraper -d /data  --media-types none --media-metadata -m 100 INSTAGRAM_ACCOUNT

This command will generate the JSON file but will not download the images, now it return nothing. 

However if I run it without " --media-types none", then it will download images and JSON. 

What would be the solution to only have the JSON without the JPG?

**Comment by malagebidi** [comment]
same problem use "--media-types none" combine with "--media-metadata"

**Comment by tomasjanu** [comment]
I have the same problem, simply this command will just create the folder **lewishamilton**, but not the json file :-(
> instagram-scraper lewishamilton --media-metadata --media-types none

**Comment by rarcega** [comment]
Fixed in v1.5.24

`pip install instagram-scraper --upgrade`
