### ISSUE TITLE
Unable to scrape `PUBLIC` user media.

### ISSUE THREAD

**Issue by Dexu5** [rarcega/instagram-scraper#190]
Hey, 

I'm an avid user of Instagram-Scraper and as a developer, I truly appreciate the efforts took by the developer. I was scraping images quite a while and I'm suddenly facing issues at `load_entry_point()`. I'll attach the screenshot of error log. Kindly, help me fixing the issue!

I tried reinstalling and upgrading the rep with latest version. I still had no success with that move.

<img width="843" alt="instagramscraperissue" src="https://user-images.githubusercontent.com/7898599/37508286-70fb71c4-2918-11e8-90dc-1987183891b1.PNG">

**Comment by shyd** [comment]
Hi, did you upgrade to v1.5.23?

**Comment by Dexu5** [comment]
@shyd Ahh my bad, hat actually worked. I tried upgrading it before to 1.5.2*. 
It was throwing me exception while performing it I believe, so I reinstalled the rep. Anyways, it works like charm!

**Comment by shyd** [comment]
Great 👍
