### ISSUE TITLE
Running scraper on Google Cloud/AWS

### ISSUE THREAD

**Issue by ChrisBuetti** [rarcega/instagram-scraper#196]
Anyone try running this on google cloud/AWS? I would like to throw it on one of those as a plan on scraping a mass amount of posts. However when I run I get the following error:

`Repeated error HTTPError('403 Client Error: Access Denied for url:`

I'm guessing it's some sort of firewall/security setting not allowing the data to come in. Any suggestions? It works fine on my local machine.

**Comment by dannyvoid** [comment]
I just started getting this error on my own machine. Not sure on the reason.

**Comment by lynxrv21** [comment]
That's not related to any cloud platform. The reason in changes on Instagram side. 
Please, see #193 
I think this issue can be closed as duplicate.

**Comment by ChrisBuetti** [comment]
@lynxrv21 Actually, it does and it has nothing to do with [#193](https://github.com/rarcega/instagram-scraper/issues/193)

It had to do with the security settings. By default, those two servers don't allow incoming and outgoing HTTP/HTTPS traffic from any IP. I used the least secure settings, any IP and all incoming/outgoing traffic, and the scraper worked.

**Comment by dany-e** [comment]
Hi,
Trying to set this up on GCP. Sort of new to it so please bear with me. 
I'm getting Errno 13:

> Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/urllib3/connectionpool.pyc'                                                                                        
> Consider using the `--user` option or check the permissions. 

Can someone help me out with setting this up on my VM. Much appreciated. Thanks
