### ISSUE TITLE
Scraping a tag raises 403 error

### ISSUE THREAD

**Issue by wietsemuizelaar** [rarcega/instagram-scraper#203]
Hi,

I'm using the 1.5.27 version, and when I want to scrape a user, everything is fine. But when trying to scrape specific tag, I get a 403 Exeception:

```
instagram-scraper takeakneenfl --tag --media-metadata --verbose 2
Searching takeakneenfl for posts: 0 media [00:00, ? media/s]WARNING: Retry after exception HTTPError('403 Client Error: Forbidden for url: https://www.instagram.com/graphql/query/?query_id=17882293912014529&tag_name=takeakneenfl&first=100&after=',) on https://www.instagram.com/graphql/query/?query_id=17882293912014529&tag_name=takeakneenfl&first=100&after=
```

**Comment by VasiliPupkin256** [comment]
It looks like `graphql/query` requests are now only allowed after authorisation. Provide the user and password of any account to scraper.

**Comment by polyzen** [comment]
You don't need authorization for user account scraping? #205 claims all requests now require login.

**Comment by VasiliPupkin256** [comment]
@polyzen authorisation was only needed to scrape stories and private profiles

**Comment by wietsemuizelaar** [comment]
@VasiliPupkin256 the update with #205 in it fixed my issue - so case closed!

**Comment by tomdyson** [comment]
It seems the Instagram API has changed again since #205 - see https://github.com/rarcega/instagram-scraper/issues/205#issuecomment-379871127
