### ISSUE TITLE
The scraper has always returned 403 errors in the last two days

### ISSUE THREAD

**Issue by malagebidi** [rarcega/instagram-scraper#204]
![403](https://user-images.githubusercontent.com/726456/38458083-3d743ea6-3acc-11e8-877b-7dad4a471f84.jpg)

It's always return a "403 Client Error: Forbidden for url: https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=5630155732&first=100&after=",  but I can visit this link in Chrome browser, does this mean that my ip is blocked?

**Comment by polyzen** [comment]
See #205.
