### ISSUE TITLE
403 Client error. Forbidden for url

### ISSUE THREAD

**Issue by Tatachiblob** [rarcega/instagram-scraper#210]
I got this error today. It was working few days ago. Most probably the API key or something.

![image](https://user-images.githubusercontent.com/20595225/38551828-c859e9ae-3cec-11e8-9e39-bca0ae274ae7.png)

**Comment by dwelina** [comment]
Same problem here. :(

**Comment by Tatachiblob** [comment]
@dwelina  I think this is the problem here.
https://techcrunch.com/2018/04/02/instagram-api-limit/

**Comment by dwelina** [comment]
Darn :(

**Comment by h-shawberry** [comment]
I’m getting the same issue. I thought maybe signing in would help the issue using the “to scrape a private user’s media when you are an approved follow” code. But it doesn’t. It says “Please verify your account at /challenge/247424506/X0a7jr9ynv/

**Comment by h-shawberry** [comment]
Forgot to mention that yesterday it was working for me so the issue has occurred overnight

**Comment by j1hwan** [comment]
@Tatachiblob Another approach is
`instagram-scraper <username> -u <your username> -p <your password>`

**Comment by LeonidIvanov** [comment]
@j1hwan it worked for you?
For me, not.

**Comment by j1hwan** [comment]
@LeonidIvanov It worked for me.
If it does not work, Try updating this package and try again.
`pip install instagram-scraper --upgrade --pre`

**Comment by DanielWFrancis** [comment]
The login worked for a few days but now I'm cut off again.

I noticed the url works fine if I open it in Chrome, so I tried copying over the headers and, with some fooling around, I've figured out that it's the cookie that is being passed that makes it work in Chrome. 

I don't know much about cookies but judging by what I'm seeing in it, I won't be able to just hardcode the cookie because it will expire. So now I'm wondering if there is any way to automate the generation of the cookie?

**Comment by LeonidIvanov** [comment]
@j1hwan I tried `pip install --upgrade --force-reinstall instagram-scraper` before the last post...

**Comment by andrewskp** [comment]
Hey, getting the same 403 issue. Weirdly enough, crawling public users works fine with and without providing login and pwd, however --tag hangs up in the same way it did for @Tatachiblob. All my packages are up to date, any idea if the issue is on my side/insta side/scraper side?

**Comment by marcoqu** [comment]
Anonymous graphql requests now need a valid `query_hash`, `csrf_token` and a header `x-instagram-gis` set to the md5 hash of `rhx_gis + ":" + csrf_token + ":" + user agent + ":" + variables`.

Here's a working example for whoever wants to implement a fix: https://gist.github.com/marcoqu/e17e1c4414f8d18e6672976d941161fa

**Comment by aspiringguru** [comment]
tried the pip reinstall above. still fails.

ERROR: Login failed for <blah>
ERROR: Please verify your account at /challenge/blah/blah/

haven't tried marcoqu's fix yet.
