### ISSUE TITLE
HTTPError('403 Client Error: Forbidden for url: https://www.instagram.com/[[username]]/?__a=1',)

### ISSUE THREAD

**Issue by DanielDimanov** [rarcega/instagram-scraper#213]
Help please! I'm trying to use this project as a dependency for my dissertation. I'm aware that the API limit has been changed, but I tried 2 different profiles and wanted to scrape someone with 7 photos and I'm still getting this. Last week worked like a charm. I have uninstalled and reinstalled it and it is updated. I'm using -u and -p, but still I'm getting the error.

**Comment by DanielDimanov** [comment]
So how can I change it? I'm using instagram-scraper {{username}} -u {{username}} -p {{password}}, so I never actually call ?__a=1 anywhere. Is there a way to avoid it?

**Comment by ngSuraj** [comment]
any leads?

**Comment by schiller** [comment]
It is possible to get the same information making the request without ?__a=1 and then extracting the data using:

json.loads( res.text.split("window._sharedData = ")[1].split(";</script>")[0])

**Comment by clublek** [comment]
I'm getting this error as well when downloading stories, for every user in my .txt file.

**Comment by neogermi** [comment]
We've built a small API trying to replace the `?__a=1` API: `https://apinsta.herokuapp.com/u/<username>`

**Comment by neogermi** [comment]
Hi in general you are free to use our service. Due to limitations from Instagram, we had to enforce some limits on our side as well. But we are happy if you list our service :-)

**Comment by coolcool1994** [comment]
@neogermi  Thank you so much! I was able to get instagram data using AFNetworking's GET method from your url. For some reason instagram original url "https://www.instagram.com/[[username]]/?__a=1" doesn't return success response. Thank you very much again.
