### ISSUE TITLE
Do you need username/ user-password if you are only searching  by tags? 

### ISSUE THREAD

**Issue by Moondra** [rarcega/instagram-scraper#217]
I looked over the README and examples contained within, but it seems like if you are only scraping tags, you don't need to enter username/user-password? 

However, if I 'm attempting to scrap tags only, I'm being prompted for an Instagram username password.
I don't have an account, so I'm wondering if I will have to create one. 

Here is my sample command:

`instagram-scraper salmon --tag -d= path/to/my/directory -t=image -m 500`

This was working fine before the update.

**Comment by jakeseaton** [comment]
This commit 

https://github.com/rarcega/instagram-scraper/commit/a96e72b49233ea010b7637784beba1d1391f61bf

made them mandatory.
