### ISSUE TITLE
instagram-scraper 1.5.34 didn't fix a thing!

### ISSUE THREAD

**Issue by MintUser34827738947** [rarcega/instagram-scraper#235]
I just downloaded the new version in hopes it will fix the problems but to my surprise it just did NOTHING! The login is still broken and when I applied @dmoreno1994 login fix it still didn't download pictures and videos from a users page. @rarcega Was that intended? I can't think of any reason why you would choose to commit a 20 day old pull request with meaningless changes and not fix the whole thing?!? You can't even appreciate the changes ...

**Comment by malagebidi** [comment]
> 2018-05-24 13:42:43,337 - instagram_scraper.app - WARNING - Retry after exception HTTPError(u'429 Client Error: - for url: https://www.instagram.com/hm/',) on https://www.instagram.com/hm
2018-05-24 13:42:48,545 - instagram_scraper.app - WARNING - Retry after exception HTTPError(u'429 Client Error: - for url: https://www.instagram.com/hm/',) on https://www.instagram.com/hm
2018-05-24 13:42:58,750 - instagram_scraper.app - WARNING - Retry after exception HTTPError(u'429 Client Error: - for url: https://www.instagram.com/hm/',) on https://www.instagram.com/hm
2018-05-24 13:43:18,921 - instagram_scraper.app - WARNING - Retry after exception HTTPError(u'429 Client Error: - for url: https://www.instagram.com/hm/',) on https://www.instagram.com/hm
2018-05-24 13:43:59,105 - instagram_scraper.app - WARNING - Retry after exception HTTPError(u'429 Client Error: - for url: https://www.instagram.com/hm/',) on https://www.instagram.com/hm

I think the 429 issue is still there, above is from my instagram-scraper.log

**Comment by oferchen** [comment]
I think 429 is just a rate limitation on instagram side because if you wait 15 minutes and retry it works

**Comment by thewracl** [comment]
I don't think OP means the 429 errors. He/she has probably the same issues as I have: With 1.5.34 you can't do a thing because of the cookie error and with the fixes from @dmoreno1994 you at least can login and get the story's of the user but it does not download any pictures!

**Comment by oferchen** [comment]
you need to add the [CSRF patch](https://github.com/rarcega/instagram-scraper/commit/05f809515f4fdbc6d58beec3234b11d2ba1672cd) for the login to work because it wasn't merged yet.

**Comment by thewracl** [comment]
No, no, no!!!! You mean this [patch](https://github.com/dmoreno1994/instagram-scraper/commit/8f125465ce76c0a6a057913b37153e6e6c3106d5) here. The other just gives an error! But as I wrote, I already applied the fix so I can login. BUUUUUUUT I can't download the media files! Can you download media files from a user? I really doubt it. Just plain simple: `instagram-scraper xxx -u yourusername -p password` and it gives shit. It can't be that @clublek @MintUser34827738947 and me are the only ones ...

**Comment by clublek** [comment]
I can confirm that the latest version does not solve anything :(

**Comment by Emalton** [comment]
Try the latest build, this was fixed.
