### ISSUE TITLE
Can't download multiple posts

### ISSUE THREAD

**Issue by Fireshadow3** [rarcega/instagram-scraper#242]
When you are trying to download a multi-photo post instagram-scraper won't work. It **won't detect** the photos.

**Comment by yudataguy** [comment]
I have the same issue, probably the code is not matching the instagram system. Haven't tested other scraper yet. This should be a top issue.

**Comment by ajinkyakolhe** [comment]
This issue seems to have been resolved, I am able to download the multiple images. Can you confirm?

**Comment by Fireshadow3** [comment]
Yes, solved! Awesome :D .

**Comment by samsepiol59** [comment]
I'm experiencing this bug right now - don't know about you guys!
