### ISSUE TITLE
[Working On] Custom Destination Per User and Media Type

### ISSUE THREAD

**Issue by Emalton** [rarcega/instagram-scraper#243]
It would be cool if we could have target directories per user and their respective media type.
### Configuration File
```
<username>:
	<media type>:<destination>
	<media type>:<destination>
```
### Configuration File Example
```
nature:
	story-image:/nature/img
	story-video:/nature/video
	default:/nature/other
```

**Comment by Emalton** [comment]
Going to start working on this today.

**Comment by VasiliPupkin256** [comment]
It can easily be done through templated filename feature, introduce a new template key say `{mediatype}` that is expanded to `story-image/story-video/image/video` then run scraper with `--template {mediatype}/{urlname}` to get the files sorted into folders

**Comment by Emalton** [comment]
That's a good idea 0:
