### ISSUE TITLE
WARNING - Failed to get media details for 

### ISSUE THREAD

**Issue by Gitiboy** [rarcega/instagram-scraper#244]
For location scrapes I am unable to extract the .json file. 

`instagram-scraper -u XXXXX-p XXXXX --location 220112037 --media-metadata --include_location --retry-forever`

Same happens when I only try to extract metdata, so including:
`--media-types none`

The instagram-scraper log shows "instagram_scraper.app - WARNING - Failed to get media details for [XXXX]" for each download.

**Comment by oferchen** [comment]
+1

**Comment by Gitiboy** [comment]
It just takes patience. The .json file will be created once all data is retrieved.

Issue closed.
