### ISSUE TITLE
challenge solving interface does not work

### ISSUE THREAD

**Issue by 4TJMn** [rarcega/instagram-scraper#251]
am i the only one that gets this error even when a valid challenge code is entered?

ERROR: Session error 1: "Please check the code we sent you and try again."

**Comment by 4TJMn** [comment]
looks like its sending something that does not belong in the code field. it works if i put the code in the app.py file directly

**Comment by clublek** [comment]
I'm having the same problem. How can i get out of this loop, or which lines do i need to change in app.py?
