### ISSUE TITLE
description/comments accompanying each photo

### ISSUE THREAD

**Issue by yipcma** [rarcega/instagram-scraper#27]
I wonder how I may get the description and comments accompanying each photo; adding onto this wonderful scraper?

Specifically, a text file of the same file name of the media where each line is a description/comment as in the instagram interface.

Thank you very much.

**Comment by rarcega** [comment]
Not quite what you're looking for but the specifying the `--media_metadata ` will fetch the associated media metadata of the posts that were scraped. You can find the description under the items[#].caption.text property.

**Comment by yipcma** [comment]
Thanks :)
