### ISSUE TITLE
How to continue an interrupted session?

### ISSUE THREAD

**Issue by N46AN** [rarcega/instagram-scraper#274]
When scraping an user with large amount of posts (several thousands), it's possible to encounter 429 errors and the download session would be interrupted. Is it possible to continue where it left off instead of start all over again? The manual was not clear on this.

Thanks!

**Comment by Nishq022** [comment]
Hey did you figure out what happens? I'm stuck on the same thing, just wanted to know if it does continue where it left off?

Thanks
