### ISSUE TITLE
(Login?) problem once again

### ISSUE THREAD

**Issue by thewracl** [rarcega/instagram-scraper#275]
Got problems again with the  Scraper. It looks like login doesn't work anymore. I'm getting this:

```
2018-08-08 03:53:17,019 - instagram_scraper.app - ERROR - User xxxxxxxx is private
2018-08-08 03:53:18,345 - instagram_scraper.app - WARNING - Retry after exception HTTPError(u'403 Client Error: Forbidden for url: https://www.instagram.com/graphql/query/?query_hash=45246d3fe16ccc6....',) on https://www.instagram.com/graphql/query/?query_hash=45246d3fe16ccc6...
```
I assume, it does not log in correctly (I'm following that user that is private) so it can't access the API

@VasiliPupkin256 
If that error only affects me let me know what further informations you need to fix that bug. Thanks!

**Comment by VasiliPupkin256** [comment]
@thewracl this affects me as well. It is not a login problem, instagram have changed the stories API. I am more specialised on a raw network infrastructure of the app, don't really know where @rarcega got those stories url etc. It would be nice if he or someone else look into it first.

**Comment by thewracl** [comment]
@VasiliPupkin256 Are you sure about that? Because when I run the network console on Firefox it shows me the exact URL than in the error log (same user) but in the browser it works. This is why I suspect a cookie is wrong and that is why it does not work. Is there a way to log the cookies it sends with the request?
Oh, and BTW, thanks for your quick reply!

**Comment by VasiliPupkin256** [comment]
@thewracl I've found that it only affects stories and scraper works fine if run with `-t image` parameter. The cookies processing logic is already there, it sets `ig_pr` cookie etc, not sure if it needs to be changed to fix the issue, but it is possible

**Comment by thewracl** [comment]
@VasiliPupkin256 I see your point. Is there a cookie that is sent only for stories or does it send the same cookies for both stories and images/video? Or maybe the content of a cookie is different when requesting stories?

**Comment by thewracl** [comment]
@VasiliPupkin256 On Firefox it additional sends the shbts cookie and the urlgen is different. Not sure if this means anything of course ...

**Comment by thewracl** [comment]
@VasiliPupkin256 I'm sorry to say that but I think you are wrong about the login part. I tried to change my scripts using  the `-t image` parameter and it works but only on public accounts! Try it on a private account which you have access to and you will see it says `User xxx is private` and you won't get the latest pictures. So this strongly suggests it is because the login process fails.

**Comment by VasiliPupkin256** [comment]
@thewracl indeed. It seems that instagram don't like the way screper process cookies or maybe it require additional authorisation somewhere.

**Comment by VasiliPupkin256** [comment]
@thewracl yes, I am not able to scrape private profiles which are authorised to a particular logged in user. instaloader support stories for example, but lack concurrent downloads and batch mode

**Comment by Eisregen04** [comment]
hey hey, it does not matter which argument I use (-t Image / -t story or -t video) always user xxx is private
I use separated commands because I want to save in separate folders
sorry for my english google helps :)

**Comment by ekalin** [comment]
My experience: I'm getting 403 errors when trying to scrape stories, as described. It works for downloading regular media (-t image), but I tried with a public user. I don't have a private user to try so I can't report on that case.

**Comment by ekalin** [comment]
I just made some tests, and it doesn't seem to be a problem with logging in. There is code to check that the login worked, the program should quit if login failed. Moreover, this is the response from the login request:

  {"authenticated": true, "user": true, "userId": "XXXXXX", "oneTapPrompt": false, "reactivated": true, "status": "ok"}

So it seems something has changed in the stories request, possibly the necessary cookies and/or their contents have changed again.

**Comment by ekalin** [comment]
This fixed it for me. I've created a pull request, but if you'd like to create one yourself, go ahead and I'll close mine.
