### ISSUE TITLE
Repeated error PartialContentException('Partial response',)

### ISSUE THREAD

**Issue by LKleemann** [rarcega/instagram-scraper#296]
Dear Sir or Madam,

I have successfully used your script for several weeks now. Thank you for the time you have invested in this project.

Since the last days I get the following error message when I start your script:

"`Repeated error PartialContentException ('Partial response',)`"

With the following command I start your script: 
"`instagram-scraper <name to download> -u <username> -p <password>`"

I use the latest version from your script.

Thank you for all the ideas on your part or from your great community.
Have a nice day

**Comment by LKleemann** [comment]
Thank you for this quick answer VasiliPupkin256.

Unfortunately, nothing has changed. The error still occurs as described above.

**Comment by VasiliPupkin256** [comment]
Have you applied the pull request? I've had this error recently and the fix solved it for me

**Comment by LKleemann** [comment]
I replaced the one line with the second line as you described it. Then I downloaded the complete script from you again. However, the same error came as above. Do you have another idea? May I know if you are currently working on the scirp?

**Comment by VasiliPupkin256** [comment]
What stack trace does it print if you choose to Abort?

**Comment by LKleemann** [comment]
This:

`Repeated error PartialContentException('Partial response',)
(A)bort, (I)gnore, (R)etry or retry (F)orever?a
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\Scripts\instagram-scraper-script.py", line 11, in <module>
    load_entry_point('instagram-scraper==1.5.39', 'console_scripts', 'instagram-scraper')()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_scraper\app.py", line 1213, in main
    scraper.login()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_scraper\app.py", line 225, in login
    self.rhx_gis = self.get_shared_data()['rhx_gis']
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_scraper\app.py", line 712, in get_shared_data
    resp = self.get_json(BASE_URL + username)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_scraper\app.py", line 204, in get_json
    resp = self.safe_get(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_scraper\app.py", line 178, in safe_get
    raise PartialContentException('Partial response')
instagram_scraper.app.PartialContentException: Partial response`

**Comment by VasiliPupkin256** [comment]
Please find the function `def safe_get` add these two lines to its code:
                
                ...
                content_length = response.headers.get('Content-Length')
                
                self.logger.info(content_length)
                self.logger.info(len(response.content))
                
                if content_length is not None and len(response.content) != int(content_length):
                ...

and tell me what it outputs to `instagram-scraper.log`

**Comment by VasiliPupkin256** [comment]
You running the original unchanged code somehow, it hasn't reach the changed lines

**Comment by LKleemann** [comment]
Okay, I'll take a look. Would you have an idea how to start the right file?

**Comment by LKleemann** [comment]
I have the script several times on the computer. But start the script from the folder where your changes in the App.py stand ... Huh?

**Comment by VasiliPupkin256** [comment]
If you are running it calling `instagram_scraper` from console then it executes code from the Pythons `Lib/site-packages/instagram_scraper/` directory, probably. It depends on your system and environment

**Comment by LKleemann** [comment]
Many thanks :) Have just tried it on another system, where it funkzuniert with your help.

Then it is now only on my own desktop PC. Can I thank you somehow?
