### ISSUE TITLE
None output using scraper with subprocess.Popen, please, advise needed.

### ISSUE THREAD

**Issue by jpegcoma** [rarcega/instagram-scraper#298]
Hi, guys.
Just wanna ask if scraper is working? 

Can't make it do stuff for me tho.
Even simple --->    instagram-scraper username_to_scrape -u login -p pass
Gives me error - PartialContentException('Partial response',)

If I use notebook:
import subprocess
import time
while True:
    p = subprocess.Popen(["instagram-scraper", "username_to_scrape", '-u login -p pass'], stdout=subprocess.PIPE)
    output = p.communicate()
    print(output)
    time.sleep(10)

it gives this output:
(b'', None)
(b'', None)

Can someone explain what I'm doing wronge, please?

**Comment by edgartaor** [comment]
It's working but right now you have to install it from the development version. That's because Instagram keep changing things and  it's hard for contributors of this repository keep the pace.

**Comment by jpegcoma** [comment]
Thank you for ASAP answer
Will do as you said
