### ISSUE TITLE
the shape of download images

### ISSUE THREAD

**Issue by rexshenn** [rarcega/instagram-scraper#30]
Hi,
This app is really nice!
But after downloading the images, i noticed that all the images are square.
You know, some users post their photos in some different shapes.
Can we solve this problem?
thank you so much.

**Comment by rarcega** [comment]
Thanks, I'm glad you found the app useful! 

I'm afraid that's not possible. All image formats are arranged into a matrix of pixels and maintain a rectangular bounding box. Image formats like PNG, GIF, and TIFF simulate the appearance of non-square image by using [transparent pixels to render the image](https://i.imgur.com/G6qoQOP.jpg). All images posted on instagram are converted to JPG format which does not support transparency.
