### ISSUE TITLE
Has anyone figured out how to 'get the x-instagram-gis' value?

### ISSUE THREAD

**Issue by zamzus** [rarcega/instagram-scraper#307]
From the code, I know that x-instagram-gis is generated by 'rhx_gis' and 'variables'。Here, I want to know why 'rhx_gis' and 'variables' ? Does anyone have a document about the process of generating 'x-instagram-gis'?

Thanks !!

**Comment by jpegcoma** [comment]
try this:
https://stackoverflow.com/questions/49786980/how-to-perform-unauthenticated-instagram-web-scraping-in-response-to-recent-priv
