### ISSUE TITLE
include / disable stories or videos

### ISSUE THREAD

**Issue by stevedub** [rarcega/instagram-scraper#33]
Would like to see the ability to choose if you would like the stories or not.
Also would like the ability to skip videos (.mp4) and only scrape for pictures.

**Comment by rarcega** [comment]
Added new argument `-t` to specify media types to scrape:
```
--media_types -t    Specify media types to scrape. Enter as space separated values. 
                    Valid values are image, video, and story.
```

Usage
```
$ instagram-scraper -t story image
```
