### ISSUE TITLE
Use in python file

### ISSUE THREAD

**Issue by suryasanchez** [rarcega/instagram-scraper#337]
Hey,

how can I use the instagram-scraper inside a python file? I would like to avoid installing the instagram-scraper through with the shell and use command line.

**Comment by reliefs** [comment]
I have same issue did you fix it?

**Comment by suryasanchez** [comment]
No, not yet. The workaround I found to use in a python file:

```
from subprocess import call
call('Your shell command', shell=True))
```

That would execute the command line from your python file. I'm still looking for a better solution though.

**Comment by reliefs** [comment]
Yeah that is not the best solution, i think that code will limit our use of instagram-scraper with other build-in python function.  This is what i have so far.
`import instagram_scraper
instagram-scraper jessicakes33`

Next step is to see if the is any connection to the instagram_scraper module from my code.

**Comment by reliefs** [comment]
Something new ? I tested the module it is connected.. I also looked inside the code, i looks like the main function only get activated on a real command but i could be wrong.

**Comment by noviluni** [comment]
Hi!

You don't have to use main() function, you have to do what main() function do.

To use it from scripts:

```python
scraper = InstagramScraper(usernames=["USERNAME"], login_user="YOUR_USER", login_pass="YOUR_PASSWORD")
scraper.scrape()
```

You can inspect `InstagramScraper` class to know more arguments like location, hashtags, etc.

Tell me if you need more help!

**Comment by reliefs** [comment]
`import instagram_scraper


scraper = InstagramScraper(usernames=["*****"], login_user="*****", login_pass="******")`

NameError: name 'InstagramScraper' is not defined

**Comment by noviluni** [comment]
Sorry I forgot to put the import statement.

I think I used:

```python
from instagram_scraper.app import InstagramScraper
```

Happy to know that you fixed it by yourself. :)

**Comment by reliefs** [comment]
No problem, thanks for the help. Also here is a full developed scraper which takes all latest images from profile 0 - 10. If anyone still needs help.
```python
import time
import instagram_scraper as insta

x = 0

profiles = ["melissaqc27", "sassy__333", "abbydowse", "torz_lyla", "alena_omovych"]
def scraper():
 #   call('instagram-scraper ' + str(thefilepath[x]), shell=True)
    imgScraper = insta.InstagramScraper(usernames=[profiles[x]],media_metadata=True,latest=True)
    imgScraper.scrape()

    print ("scraped")
def main():
    scraper()

while x < 10:
    main()
    x = x + 1
    time.sleep(60)
```

**Comment by suryasanchez** [comment]
Thanks a lot! 

Here is my result to scrape meta_data of the 3 last media of two accounts' profile.

```
import time
import instagram_scraper as insta

insta_profiles = ["profile1", "profile2"]
number_last_photos = 3

def scraper():
 #	call('instagram-scraper ' + insta_profiles + ' -m ' + number_last_photos + ' -u 0 -p 0 -t none --media-metadata', shell=True)
    imgScraper = insta.InstagramScraper(usernames=[insta_profiles[x]],maximum=number_last_photos,media_metadata=True,
    									latest=True,media_types=['none'])
    imgScraper.scrape()

    print ("scraped " + str(number_last_photos) + " from " + insta_profiles[x])
def main():
    scraper()

for x in range(len(insta_profiles)):
    main()
    time.sleep(1)
```

I don't know if it can help you but I don't download all the media but just make a list of URL like this:

```
path_to_json = insta_profiles + '/' + insta_profiles + '.json'
list_url_photos = []

# read json file and create a list with the urls
with open(path_to_json) as json_file:  
    data = json.load(json_file)
    for i in range(len(data)):
        list_url_photos.append(data[i]['display_url'])
```

**Comment by reliefs** [comment]
I just finished my bot which automatic scrape and then repost the scraped images on instagram.
Maybe you can use something :) Your work did 30% of my job thanks :)
```python
import time
import instagram_scraper as insta
import json
from subprocess import call

insta_profiles = ["melissaqc27", "sassy__333", "abbydowse", "torz_lyla", "alena_omovych"]
number_last_photos = 3

def scraper():
 #call('instagram-scraper ' + insta_profiles + ' -m ' + number_last_photos + ' -u 0 -p 0 -t none --media-metadata', shell=True)
    imgScraper = insta.InstagramScraper(usernames=[insta_profiles[x]], maximum=number_last_photos, media_metadata=True, latest=True,media_types=['image'])
    imgScraper.scrape()
    # Take last json image data and post in instagram images,  tags and decription
    with open(insta_profiles[x] + '/' + insta_profiles[x] + '.json', 'r') as j:
        json_data = json.load(j)
        newstr = (json_data[0]["display_url"])
        imgUrl = newstr.split('?')[0].split('/')[-1]
        imgTags = (json_data[0]["tags"])
       # imgDescription = (json_data[0]["description"])
        call('instapy -u yourusername -p yourpassword -f ./' + insta_profiles[x] + '/' + imgUrl +' -t "#model #models #Modeling #modelo #modellife #modelling #modelagency #Modelos #modelphotography #modelsearch #ModelStatus #modelingagency #modelfitness #ModelsWanted #modelshoot #modella #modelmanagement #modelscout #modeltest #modelindonesia #modele #modelife #modelmayhem #modelgirl #modell #modelslife #modelkids #modelcall #modelpose #ModelBehavior"', shell=True)
        print(imgUrl,imgTags,json_data)

    print ("scraped " + str(number_last_photos) + " from " + insta_profiles[x])
def main():
    scraper()

for x in range(len(insta_profiles)):
    main()
    time.sleep(1500)
```

Requirements: 
pip install instapy-cli

**Comment by Endcoo** [comment]
Hi guys, any idea if it's possible to set the --retry-forever option when using the instagramscraper class? My scrapper is getting interrupted by the "Repeated error (A)bort, (I)gnore, (R)etry or retry (F)orever?" dialogue. Thanks in advance.
