### ISSUE TITLE
410 Client Error: Gone for url:

### ISSUE THREAD

**Issue by Zachary24** [rarcega/instagram-scraper#343]
it's occurring for multiple accounts and has been since the last update, it'll dl all the posts then freeze at the last few giving an error like 

`Searching gabbyschey for profile pic: 100% 1/1 [00:00<?, ? images/s]
Searching gabbyschey for posts: 1380 media [01:33, 14.71 media/s]
Downloading:  65%|██████▌   | 903/1381 [01:18<01:31,  5.23it/s]
Repeated error HTTPError('410 Client Error: Gone for url: https://scontent-ort2-1.cdninstagram.com/vp/0410e96db765f9b392099efb2025f96b/5D08A6F2/t51.2885-15/e35/35000790_2173628012882309_6153574428673310720_n.jpg?_nc_ht=scontent-ort2-1.cdninstagram.com&se=7&ig_cache_key=MTgxMTk2NzY5Njk0NzMxMDkyNA%3D%3D.2')
Downloading: 100%|█████████▉| 1380/1381 [02:21<00:00,  4.99it/s]`

and it only stops when there is user interaction, ie doesn't error out

**Comment by florinbarbisch** [comment]
It's really anoying, an automatic error handling for known errors like 410 would help, even if it's hardcoded.

**Comment by VasiliPupkin256** [comment]
What is it? The photo was removed during the download process?

**Comment by florinbarbisch** [comment]
@VasiliPupkin256 I think so. But you should first verify this.
It occured 6 times while downloading 75000 pictures/videos of 61 accounts.
It does occure for pictures and videos.

[instagram-scraper.log](https://github.com/rarcega/instagram-scraper/files/3117876/instagram-scraper.log) without content-length warnings (I got 47900 of them🤔).

**Comment by VasiliPupkin256** [comment]
Do you know which username and media caused this?

**Comment by florinbarbisch** [comment]
No I don't know. But it was not only one account.

**Comment by VasiliPupkin256** [comment]
We need to know how reproduce an error to fix it

**Comment by florinbarbisch** [comment]
I can reproduce the error. The profile: valentinaferragni

Searching valentinaferragni for posts: 3327 media [02:12, 25.11 media/s]
Downloading:  97%|█████████▋| 3216/3328 [04:27<00:18,  6.07it/s]
Repeated error HTTPError(u'410 Client Error: Gone for url: https://scontent-frx5-1.cdninstagram.com/vp/9059f788a66753751a7e1884e46bd223/5D704E67/t51.2885-15/e15/10995241_1072678636091310_1512345864_n.jpg?_nc_ht=scontent-frx5-1.cdninstagram.com&ig_cache_key=OTMxODE2ODYxMjA4MTE5ODY5.2',)

The error occurs also in the chrome developer tools, you just need scroll really long.

**Comment by VasiliPupkin256** [comment]
The media causing this is https://www.instagram.com/p/zuen-QB4o9/ and it seems that the file was really lost by instagram and can't be downloaded
