### ISSUE TITLE
instagram-scraper: error: unrecognized arguments: --profile-metadata

### ISSUE THREAD

**Issue by Greenbald** [rarcega/instagram-scraper#352]
I need to get the number of followers and following from the user's profile. Whe I try to use the --profile-metadata option, I receive this error:

**instagram-scraper: error: unrecognized arguments: --profile-metadata**

I'm using this string to run the program:

"instagram-scraper -f {0} -d {1} -n -u {2} -p {3} --retry-forever --latest --profile-metadata --comments -t image"

**Comment by ttresslar** [comment]
I have the same issue. Has the feature been depreciated or something?

**Comment by ttresslar** [comment]
Wow....never mind...solved by updating.
