### ISSUE TITLE
Preserve username directory names when -d flag is specified.

### ISSUE THREAD

**Issue by corymb** [rarcega/instagram-scraper#36]
Hey! Great program :)

I need to preserve the username subdirectories when specifying a root directory. It's pretty straightforward and I've sent you a PR if you think it's something other people might use too.

Thanks for your work!

**Comment by rarcega** [comment]
Looks good. Thanks for your contribution! I've merged the pull request.

**Comment by corymb** [comment]
My first contribution to anything open source - thank you for making it so cool!
