### ISSUE TITLE
I wish we could also download the caption

### ISSUE THREAD

**Issue by george-weare8** [rarcega/instagram-scraper#374]
Awesome scraper! Love it :-)

I wish for each photo we could also download the caption! Would that be something to consider adding?

**Comment by luizfdflores** [comment]
This is already possible! Be sure to add --media-metadata to the command line. It adds a json file with informations for every image/ video. I find it very useful and I was able to retrieve the image caption!

**Comment by george-weare8** [comment]
Nice! Works :-)
One more you might already added to this awesome script, can I limit the results? I don't want for example to download hundreds or thousands of posts.

**Comment by luizfdflores** [comment]
@george-weare8 yes, you can limit the results by adding --maximum option to your command line.

**Comment by george-weare8** [comment]
Pure awesomeness!
