### ISSUE TITLE
KeyError: 'rhx_gis'

### ISSUE THREAD

**Issue by Nicksxs** [rarcega/instagram-scraper#377]
Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 1362, in main
    scraper.authenticate_with_login()
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 252, in authenticate_with_login
    self.rhx_gis = self.get_shared_data()['rhx_gis']
KeyError: 'rhx_gis'

**Comment by Nicksxs** [comment]
instagram-scraper-1.6.0

**Comment by igorveremsky** [comment]
same, looks like instagram from now not provided "rhx_gis" token in "window._sharedData"

**Comment by yummypasta** [comment]
Can confirm. I have had no problems with this before today. Possibly because of Instagram's planned deprecation of the legacy API this uses?

**Comment by inter-activ** [comment]
Yes, I can't find "rhx_gis" in source code...

**Comment by reliefs** [comment]
same problem

**Comment by AntoineMau** [comment]
You just have to replace all rhx_gis variables or fields by empty strings and it does the work, until cleaner fix !

**Comment by reliefs** [comment]
> You just have to replace all rhx_gis variables or fields by empty strings and it does the work, until cleaner fix !

Thanks, works :)

**Comment by george-weare8** [comment]
Same here, will the fix be available via PIP soon?

**Comment by bateternal** [comment]
> You just have to replace all rhx_gis variables or fields by empty strings and it does the work, until cleaner fix !

tnx man :))))))

**Comment by joootdooot** [comment]
Fingers crossed for the pip update

**Comment by iteimouri** [comment]
I think I have the same problem: 
`Traceback (most recent call last):
  File "/anaconda2/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==1.6.0', 'console_scripts', 'instagram-scraper')()
  File "/anaconda2/lib/python2.7/site-packages/instagram_scraper-1.6.0-py2.7.egg/instagram_scraper/app.py", line 1367, in main
    scraper.authenticate_as_guest()
  File "/anaconda2/lib/python2.7/site-packages/instagram_scraper-1.6.0-py2.7.egg/instagram_scraper/app.py", line 234, in authenticate_as_guest
    self.rhx_gis = self.get_shared_data()['rhx_gis']
KeyError: 'rhx_gis'`

**Comment by bennyblanco4** [comment]
> > You just have to replace all rhx_gis variables or fields by empty strings and it does the work, until cleaner fix !
> 
> Thanks, works :)
> 
> Here is a working fix:
> https://github.com/instagrambot/instabotai/tree/master/instagram_scraper

Still doesn't work for me. Any ideas why ?

**Comment by mannasoumya** [comment]
> > > You just have to replace all rhx_gis variables or fields by empty strings and it does the work, until cleaner fix !
> > 
> > 
> > Thanks, works :)
> > Here is a working fix:
> > https://github.com/instagrambot/instabotai/tree/master/instagram_scraper
> 
> Still doesn't work for me. Any ideas why ?

Doesn't work for me as well. ☹️

**Comment by joootdooot** [comment]
Instagram is probably clamping down on free use of their of their API

**Comment by AKwoKWH** [comment]
checking others' code
https://github.com/instagrambot/instabotai/commit/2ded0bb282dd486cbc60a19bf425c3f1be89ae21
seem a quick fix
![image](https://user-images.githubusercontent.com/23435188/58186359-506b2700-7ce7-11e9-9d0c-a954c78ec536.png)

**Comment by seekpedro** [comment]
Still not working for me. Keep getting this error:

  File "c:\users\ibpad\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 252, in authenticate_with_login
    self.rhx_gis = self.get_shared_data()['rhx_gis']
KeyError: 'rhx_gis'

I'm using https://github.com/instagrambot/instabotai/commit/2ded0bb282dd486cbc60a19bf425c3f1be89ae21 this version as of it now

**Comment by reliefs** [comment]
> > You just have to replace all rhx_gis variables or fields by empty strings and it does the work, until cleaner fix !
> 
> Thanks, works :)
> 
> Here is a working fix:
> [instagrambot/instabotai:instagram_scraper@`master`](https://github.com/instagrambot/instabotai/tree/master/instagram_scraper) [](/instagrambot/instabotai/tree/HEAD@{2019-05-16T10:32:21Z}/instagram_scraper)

Lol i have been trying to fix this for 4 days again.. forgot i once had fixed it, was looking for a fix.. Guys this is why you should always document your fix.. Thanks to myself.
