### ISSUE TITLE
What if i want to scrape only stories?

### ISSUE THREAD

**Issue by s2c130050131527** [rarcega/instagram-scraper#39]
I want to scrape the stories of users daily.

**Comment by rarcega** [comment]
Added new argument `-t` to specify media types to scrape:
```
--media_types -t    Specify media types to scrape. Enter as space separated values. 
                    Valid values are image, video, and story.
```

Example Usage
```
$ instagram-scraper -t story
```

**Comment by marctuinier** [comment]
I don't understand how you'd write the request if I'd want to pull all Stories with the Redbull hashtag. Currently, it only pulls Instagram posts. hope you can help out :)

The following doesn't work:

$instagram-scraper -t story --tag redbull -u marctuinier -p ****

https://www.instagram.com/explore/tags/redbull/
