### ISSUE TITLE
Why it download only single image?

### ISSUE THREAD

**Issue by mrgloom** [rarcega/instagram-scraper#398]
This command downloads only single strange image:
`time instagram-scraper shnurov -d data/images/shnurov`

But this works fine:
`time instagram-scraper -f data/user_list.txt -d data/images/shnurov -t image`
but in this case I can't control output dir for each user.

**Comment by florinbarbisch** [comment]
because the user `shnurov` has no media, so the only image being downloaded is the users profile photo.
