### ISSUE TITLE
Unable to get all the images of Carousel except the first one

### ISSUE THREAD

**Issue by Vgandhi9** [rarcega/instagram-scraper#40]
First of all, I would like to thank for a great scraper.
Using the scraper I'm able to get only the first image of the carousel. Can someone tell me how to get all the remaining images of the carousel?

Thanks in advance.

**Comment by s2c130050131527** [comment]
maybe a private account

**Comment by Vgandhi9** [comment]
No that was not the case. 

Let's take Instagram account of `audi` as example, the [10th post](https://www.instagram.com/p/BQ6HvczBfWP/) is a carousel. Now how do I scrap all the 6 images of that post?

**Comment by rarcega** [comment]
Added support for scraping carousel media in 1.1.1
