### ISSUE TITLE
Repeated error HTTPError 429 Client Error

### ISSUE THREAD

**Issue by MihaelaNichita** [rarcega/instagram-scraper#403]
I'm trying to get POSTS (without media) and comments from a user on Instagram.

**How I'm running it:**
instagram-scraper _vip_ -u _me-the-stalker_ -p _password_ --comments --media-types none --no-check-certificate

**What I get:**
![image](https://user-images.githubusercontent.com/40822291/60061309-58aaed80-96fd-11e9-9a99-6824d05545a6.png)

**Comment by MihaelaNichita** [comment]
Just tried again and again, and finally got it working. It seems that my rate of requests has been too high and the server was not willing to accept it.

**Comment by MihaelaNichita** [comment]
I figured out why it was actually happening. It was because I was trying to access Instagram pages from the browser at the same time.

**Comment by jasonkhanlar** [comment]
I notice this same error consistently every time with only -i -u -p and --comments but only for some users, such as miia_draws_

Adding --verbose 2 shows the error appear several times more during the querying process.
