### ISSUE TITLE
Downloading:   0%|          | Anyone else experieincing this?

### ISSUE THREAD

**Issue by beakwood** [rarcega/instagram-scraper#409]
Initially, I thought my -f file.txt was causing the error of not downloading, even though it was working two days or so ago. Then, I inputted a single user, and still the same thing. This is public profiles. Any idea why? also used VPN, and the same thing is happening.

**Comment by yeyicheng** [comment]
Save here. It was working yesterday.

**Comment by florinbarbisch** [comment]
Facebook's services (Facebook, Instagram, WhatsApp...) have currently trouble running some services, this should be temporarily. Just google "Instagram down".

**Comment by beakwood** [comment]
I figured as much but didn't think this would be affected. But guess it is the case, thanks for chiming in.
