### ISSUE TITLE
Can't scrape posts - Error 403 recieved

### ISSUE THREAD

**Issue by MathieuSeraphim** [rarcega/instagram-scraper#424]
I get the following error when scraping:
`Repeated error HTTPError(u'403 Client Error: Forbidden for url: https://www.instagram.com/graphql/query/?query_hash=45246d3fe16ccc65[..]',)
(A)bort, (I)gnore, (R)etry or retry (F)orever?
`
Other people I know have the same issue, and a similar issue has been reported for a PHP-based Instagram scraper:
https://github.com/postaddictme/instagram-php-scraper/issues/523
Any ideas?

**Comment by thewracl** [comment]
I can confirm that. Since about 10 hours ago. It seems 403 errors only show up for private accounts. Public accounts and private accounts where you have no access seem unaffected.

**Comment by benlumley** [comment]
User of the linked PHP lib here, found this thread so thought I'd update in case it helps...

You appear to need x-csrftoken now, even when you aren't logged in. Early tests suggest any value works....  see 

https://github.com/postaddictme/instagram-php-scraper/issues/523#issuecomment-519836041

**Comment by VasiliPupkin256** [comment]
The strange thing is that we have the `X-CSRFToken` but not using it and overwrite session.headers all the time.

I've changed all the `self.session.headers = ...` to `self.session.headers.update(...)` and it start to scrape again, but not sure if it doesn't introduce more problems

**Comment by mabbasi90** [comment]
> 
> 
> The strange thing is that we have the `X-CSRFToken` but not using it and overwrite session.headers all the time.
> 
> I've changed all the `self.session.headers = ...` to `self.session.headers.update(...)` and it start to scrape again, but not sure if it doesn't introduce more problems

I saved req.cookies['csrftoken'] in self.csrftoken as a new variable, in authenticate_as_guest and used it in 
self.session.headers.update({'X-CSRFToken': self.csrftoken})
in safe_get before calling self.session.get and it works OK, at least for scraping comments.

**Comment by mabbasi90** [comment]
if fixed self.session.headers.update({'user-agent': CHROME_WIN_UA}) everywhere but got PartialResponseException in safe_get, maybe forgot it somewhere, but it works now anyway, thanks.

**Comment by Jobeo** [comment]
> if fixed self.session.headers.update({'user-agent': CHROME_WIN_UA}) everywhere but got PartialContentException ('Partial Response') in safe_get, maybe forgot it somewhere, but it works now anyway, thanks.

I had this same PartialContent issue.  Seems related to this line:

`if content_length is not None and len(response.content) != int(content_length)`

Strange thing is the length of response.content is BIGGER than Content-Length from the headers.  I'm not sure why that would be but it's probably not consistent with a partial content exception which would indicate we received too little content.  I changed that line to:

`if content_length is not None and len(response.content) < int(content_length):`

And it got things working again

**Comment by ano0** [comment]
weird that i dont see this yet
