### ISSUE TITLE
Pictures will not be downloaded

### ISSUE THREAD

**Issue by LKleemann** [rarcega/instagram-scraper#426]
Good evening dear community,
I hope you can help me. Since yesterday evening no images are downloaded, but no error is displayed. See the following output:

`Searching user1 for profile pic: 100% 1/1 [00:00<00:00, 404.19 images/s]
Searching user1 for stories: 0 media [00:00, ? media/s]
Searching user1 for posts: 0 media [00:00, ? media/s]
Downloading: 100%|##########| 1/1 [00:00<00:00, 544.50it/s]
Searching user2 for profile pic: 100% 1/1 [00:00<00:00, 427.08 images/s]
Searching user2 for stories: 0 media [00:00, ? media/s]
Searching user2 for posts: 0 media [00:00, ? media/s]
Downloading: 100%|##########| 1/1 [00:00<00:00, 579.00it/s]
Searching user3 for profile pic: 100% 1/1 [00:00<00:00, 94.91 images/s]
Searching user3 for stories: 0 media [00:00, ? media/s]
Searching user3 for posts: 0 media [00:00, ? media/s]
Downloading: 100%|##########| 1/1 [00:00<00:00, 721.91it/s]
Searching user4 for profile pic: 100% 1/1 [00:00<00:00, 249.69 images/s]
Searching user4 for stories: 100%|##########| 1/1 [00:00<00:00, 998.41 media/s]
Searching user4 for posts: 0 media [00:00, ? media/s]
Downloading: 100%|##########| 1/1 [00:00<00:00, 678.03it/s]
Searching user5 for profile pic: 100% 1/1 [00:00<00:00, 202.48 images/s]
Searching user5 for stories: 0 media [00:00, ? media/s]
Searching user5 for posts: 0 media [00:00, ? media/s]
Downloading: 100%|##########| 1/1 [00:00<00:00, 251.70it/s]`

I have replaced the usernames. There are private and public users.

I hope you can help me
A beautiful Sunday evening

**Comment by ano0** [comment]
maybe they are testing something only for some users then. everything is working fine for me.
