### ISSUE TITLE
[SOLVED] Running application after installation

### ISSUE THREAD

**Issue by gcakir** [rarcega/instagram-scraper#435]
After successfully executing:

`python setup.py install`

I am unable to run the app.
How do I launch the application?
None of the commands below work:

```
instagram-scraper
python -m instagram-scraper
python -m instagramscraper
python -m instagram_scraper
```

The following command gives the following error:
`python -m instagram_scraper`

> C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe: No module named instagram_scraper.__main__; 'instagram_scraper' is a package and cannot be directly executed

When I run:
`instagram-scraper`

I get:
> 'instagram-scraper' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by gcakir** [comment]
It works when I execute:
`python app.py <username>`

But I can't get it to work as described above. How can I execute it without executing app.py?

**Comment by gcakir** [comment]
OK. I solved it by using the following command
python -m instagram_scraper.app <username>

I had to add ".app" at the end of the module name to get it working.

**Comment by senlsx** [comment]
how to use it in linux
it's useful for mine:
`python3 -m instagram_scraper.app <username>`

**Comment by gcakir** [comment]
@senlsx Thank you very much for the info.
