### ISSUE TITLE
Unable to scrape, bad request errors.

### ISSUE THREAD

**Issue by akhepcat** [rarcega/instagram-scraper#450]
Started receiving this error:

 instagram_scraper.app - WARNING - Retry after exception HTTPError('400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/users/XXXXXXXXX/info/',) on https://i.instagram.c
om/api/v1/users/XXXXXXXXX/info/

as of yesterday.  Can't scrape anymore.  Guessing they've changed the API endpoint requirements yet again...

**Comment by carellano** [comment]
change the user agent 

Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 105.0.0.11.118 (iPhone11,8; iOS 12_3_1; en_US; en-US; scale=2.00; 828x1792; 165586599)

**Comment by elahimanesh** [comment]
> change the user agent
> 
> Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 105.0.0.11.118 (iPhone11,8; iOS 12_3_1; en_US; en-US; scale=2.00; 828x1792; 165586599)

I changed CHROME_WIN_UA in constants.py by your user agent.
But not working.

**Comment by akhepcat** [comment]
I changed both CHROME_WIN_UA  and STORIES_UA.

Things seem to be mostly working with that change.
