### ISSUE TITLE
Ability to get list of media urls for profile

### ISSUE THREAD

**Issue by rusllonrails** [rarcega/instagram-scraper#47]
Hey guys,

I have a question: Is it possible to get just a list of media urls (without downloading of them)?

Smth like:
```
$ instagram-scraper officialslystallone --urls-only
```

Probably put `item['urls']` from
https://github.com/rarcega/instagram-scraper/blob/master/instagram_scraper/app.py#L418
to separated method available in CLI.

Thanks :beer:

**Comment by rarcega** [comment]
Yes this can be implemented as a new feature. What is the expected output and structure? For example it can be output as json file or text file separated by new lines.

**Comment by rusllonrails** [comment]
Hey man. Thanks for reviewing my question )

I thinks it can be like:

*Request:*
```
$ instagram-scraper officialslystallone --urls-only
```
*JSON Response:*
```
{
  urls: [
     "https://scontent-frt3-1.cdninstagram.com/t51.288515/s640x640/e15/18299316_1362094797170762_3887433255330250752_n.jpg",
      "https://scontent-frt3-1.cdninstagram.com/t51.288515/s640x640/sh0.08/e35/c0.135.1080.1080/18252502_1755496524762904_1541627542522298368_n.jpg",
      .... so on
  ],
  "has_more": true (or false),
  "next_page": 2,
  "total_pages": 10
}
```
Ability to paginate would be brilliant - but I understand that it can be not easy to implement.
So first version can be without pagination :+1: 

Thanks BRO :beers:  Super app! :100:

**Comment by rarcega** [comment]
Use the following to get the media urls:

`$ instagram-scraper officialslystallone --media_metadata -t none`

A file named `<username>.json` will be produced in the destination directory.

**Comment by rusllonrails** [comment]
@rarcega thanks :+1: 

Works good :100: 
Small q: is it possible to implement kind a pagination like?

```
$ instagram-scraper officialslystallone --media_metadata -t none -page 2 -limit 20 
```
Thanks

**Comment by rarcega** [comment]
You can use the `-m` argument to specify the maximum number of items to scrape:
```bash
$ instagram-scraper officialslystallone --media_metadata -t none -m 20 
```
which will get the 20 most recent posts.

**Comment by rusllonrails** [comment]
@rarcega thanks BRO :+1:
