### ISSUE TITLE
disable download on photos

### ISSUE THREAD

**Issue by reliefs** [rarcega/instagram-scraper#473]
Hi i want to disable the download of photos but still download all photos meta-data how is that possible ?

Thanks

**Comment by micuat** [comment]
I wrote the solution here https://github.com/rarcega/instagram-scraper/issues/475#issuecomment-574315298

**Comment by reliefs** [comment]
Thanks. Do you know if it denies the "download" request, or actually still does the request but just doesn't download it?

I know this sound stupid, but i think the less request sent, the better it is to prevent blocking.

**Comment by reliefs** [comment]
tested send same amount of requests, thanks.
