### ISSUE TITLE
Ability to search users by name (partial match)

### ISSUE THREAD

**Issue by rusllonrails** [rarcega/instagram-scraper#48]
Hey guys,

I have a question: Is it possible to get search in user profiles by keyword?

Smth like:
```
$ instagram-scraper sta --urls-only
```
returns smth like in JSON:

![example](https://cloud.githubusercontent.com/assets/358508/25739551/05e8c236-318b-11e7-827c-66a8b5845582.png)

Thanks :beer:

**Comment by rarcega** [comment]
If you have `curl` or `wget` available:

```bash
curl "https://www.instagram.com/web/search/topsearch/?context=blended&query=sta" -o output.json
```
```bash
wget -O output.json "https://www.instagram.com/web/search/topsearch/?context=blended&query=sta"
```

**Comment by rusllonrails** [comment]
@rarcega super BRO! :beer: 
Thank you very much, you suggestion works perfect! :100:
