### ISSUE TITLE
Does proxy even work?

### ISSUE THREAD

**Issue by reliefs** [rarcega/instagram-scraper#480]
Let me explain i am scraping with proxy.. I both use VPN on OS and proxy for the bot.. So two ip changes..

I started to get errors because scraping to many, then i changed the VPN and it worked again, this should not happen if the proxy worked correct.

**Comment by VasiliPupkin256** [comment]
So you were blocked by ip, then you've changed ip and it worked again as expected. What is the issue?

**Comment by reliefs** [comment]
The ip was blocked, but i never changed the ip.. i changed the vpn.. which is not releated to instagram-scraper.. 

That means the ip in instagram-scraper was never "working" really. 

Here is my implementation:
proxies = '{"http": "http://username:password@1**.1**.161.94:*1**5" }'


os.system("instagram-scraper " + "'"+user+"'" + " --profile-metadata --media-metadata --media-types none --maximum 200 --retry-forever --proxies " + "'"+proxies+"'")

**Comment by VasiliPupkin256** [comment]
So the proxy was after vpn or before? http proxies also pass your ip in the request header field `X-Forwarded-For` and instagram may've reacted on this. I don't see how it can be a scrapper issue if it works and establish a connection.

**Comment by reliefs** [comment]
The proxy connect after the vpn has been enabled.. 

But when i scraped the vpn got detected and blocked and not the proxy.. which means the proxy is not activated right ?

**Comment by VasiliPupkin256** [comment]
If it doesn't use proxy change http key to https

**Comment by reliefs** [comment]
no issues so far thanks for the help.. Hope this thread helps others.. Really noob question from me should had debugged more before asking it.
