### ISSUE TITLE
Timestamp format?

### ISSUE THREAD

**Issue by huayicodes** [rarcega/instagram-scraper#517]
I scrape some image meta data with --media-metadata. In the Json file, the timestamp of the images is: 
"taken_at_timestamp": 1581884112

Does anyone know how to translate that string of numbers into something that makes sense?

**Comment by Aaronzinhoo** [comment]
The time is represented in unix time and can be converted using the datetime pakcage within python.

**Comment by Aaronzinhoo** [comment]
You can parse and convert it like so:
```
from datetime import datetime
timestamp = "1284101485"
print(datetime.utcfromtimestamp(int(timestamp)).strftime('%Y-%m-%d %H:%M:%S'))
```

**Comment by AlexNik** [comment]
@huayicodes try this site
https://timestamp.online/

**Comment by huayicodes** [comment]
@Aaronzinhoo @AlexNik Thanks for the explanations and showing me how it's done!!
