### ISSUE TITLE
max requests / time

### ISSUE THREAD

**Issue by flosn25** [rarcega/instagram-scraper#52]
i'm using the getAccountById function in a php script. since i need to start the request every 1-3 seconds to have the most recent posts for a hashtag, i face problems of instagram limits the amount of max. request within a specified time limit. after a while of running requests with your script, i'm getting 

"Catchable fatal error: Object of class stdClass could not be converted to string in D:\Application\xampp\htdocs\src\InstagramScraper\Instagram.php on line 316"

after this, it takes ~30seconds to 1 minute, to have a successfull request. do you a suggestion for this problem?
thanks in advance ! :)

**Comment by rarcega** [comment]
Sounds like you have the wrong project. This is a command-line application to scrape instagram using python and does not use php. You may want to check out the following issue https://github.com/postaddictme/instagram-php-scraper/issues/69 which appears to be similiar to what you're experiencing.

**Comment by flosn25** [comment]
i gosh, i mixed up the two projects. thank you
