### ISSUE TITLE
I dont really know how to use this

### ISSUE THREAD

**Issue by jingwuk** [rarcega/instagram-scraper#527]
im new to this post n i would really like to know how to use this thing

ive install the phyton n download the instagram-scraper with pip, n have install the setup.py. n i started typing in python "instagram-scraper demo-ig-scraper" just like the gif at github
n it comes to syntax error. 

pls dont judge im a noob to this, 
im just looking how to scrape a comment from a certain post on instagram using this tool/apps.
i really need ur help guys

**Comment by Aaronzinhoo** [comment]
to demo the scrapper you can just try a simple request like:

```
instagram-scraper --tag ucla -m 10 --media-metadata
```
Although this is a python program, its usable from the command line directly. If you do not understand what the args are, i suggest reading the readme! Hope this helps

**Comment by jingwuk** [comment]
thank you that was very helpful, I started to figure out how to use this.

ive been trying to get comments from my instagram account, but its getting error like the username doesnt exist. the command-line ive tried to run : 
`instagram-scraper bakar_gas -m 1 --media-metadata --comments`

n is there any module for this instagram-scraper that i can use to do the python program, i need something to guide me how to do it

sorry ive been off to search for more tools to do this,  but ive ended with none of them working haha (maybe syntax error too) @Aaronzinhoo

**Comment by Aaronzinhoo** [comment]
try putting an "@" in front of the user name and it should work

**Comment by jingwuk** [comment]
it doesnt work too with "@" in front of it.
![image](https://user-images.githubusercontent.com/63393986/80689122-0691e000-8af7-11ea-97e3-65ce45b9622c.png)

**Comment by Aaronzinhoo** [comment]
hmm `instagram-scraper bakar_gas -m 1 --comments` ran just ran fine for me.

**Comment by Aaronzinhoo** [comment]
I copied and pasted your code as well and it worked, do you mind telling me the version of python and Instagram scraper you are using?

**Comment by jingwuk** [comment]
Python 3.8.2 and i think ive done the instagram-scraper upgrade command line

**Comment by jingwuk** [comment]
ok i know the problem. 

it seems that the `instagram-scraper <username>` doesnt work for me.
it needs to login first, or at least given the wrong id and pass worked for me
`instagram-scraper <username> -u <your username> -p <your password>`
thankyou for your help @Aaronzinhoo
