### ISSUE TITLE
Repeated output statements

### ISSUE THREAD

**Issue by Aaronzinhoo** [rarcega/instagram-scraper#539]
When scaping profile data user, (not logged in) not found errors occur and it just prints one line, but eventually, after multiple errors, the print statements will repeat over several lines which eventually prompts a rate limit to be reached. Is this an issue with the multithreading?

**Comment by VasiliPupkin256** [comment]
It should print only one user not found error for each user in the list. How do you run it?

**Comment by Aaronzinhoo** [comment]
I run it as an imported module:

`
   while not done:
        current_index = get_recent_user_index(users, destination)
        print("Index: ", current_index, flush=True)
        proxies = switch_proxy(proxy_list, current_proxy)
        current_proxy = proxies["https_proxy"].splitt("://")
        scraper = InstagramScraper(
            login_user="hikaru_utada_fan93",
            login_pass="Gorillaz",
            destination=destination,
            media_types=[],
            retry_prompt_selection="E",
            usernames=users[current_index:],
            profile_metadata=True,
            proxies=json.dumps(proxies),
        )
....
`

**Comment by VasiliPupkin256** [comment]
If you scrape with the same user credentials in parallel it will trigger the rate limit of course

**Comment by Aaronzinhoo** [comment]
I am not authenticating the user login since I am only getting profile data

**Comment by Aaronzinhoo** [comment]
I am actually not even authenticating as a guest either since for some reason I hit rate limits a lot soon than without authentification at alll

**Comment by Aaronzinhoo** [comment]
I have another process that I am doing scraping of post metadata with also and it runs into the same issue. The rate limits are not the issue here though, it seems that the number of processes increase over time.

**Comment by VasiliPupkin256** [comment]
Are you using anonymous proxies that do not expose your IP to the instagram through the `X-Forwarded-For` field?

**Comment by Aaronzinhoo** [comment]
No I am not, I assumed that setting the proxy parameter correctly would be enough. I also use this function but it does not seem to change much
```
def switch_proxy(proxy_list, current_proxy=None):
    proxy = current_proxy
    while proxy == current_proxy:
        proxy = proxy_list[random.randint(0, len(proxy_list) - 1)]
    http_proxy = "http://" + proxy
    https_proxy = "https://" + proxy
    os.environ["http_proxy"] = http_proxy
    os.environ["https_proxy"] = https_proxy
    return {"http": http_proxy, "https": https_proxy}

```

**Comment by Aaronzinhoo** [comment]
It seems, Once I catch an exception from InstagramScraper and restart the scraping it doubles the print statements. I am only using a single process in this loop so it is interesting that this is occuring....

**Comment by VasiliPupkin256** [comment]
The rete limit is imposed by the instagram server not the scraper. If it somehow manages to identify you it will block you. If your proxies aren't anonymous it may catch you reading the `X-Forwarded-For` http request field. This is my guess. I am not sure how else it can identify that all this requests is done by you alone and limits you.

What do you mean under "doubles the print statements"?

**Comment by Aaronzinhoo** [comment]
```
ERROR: Error getting user details for __tai.yuu. Please verify that the user exists.    
ERROR: Error getting user details for nk811m. Please verify that the user exists. 
ERROR: Error getting user details for __1995r.__. Please verify that the user exists.
ERROR: Error getting user details for _kk17.sa84. Please verify that the user exists.
ERROR: Error possible rate limit reached! Try scraping again later                        
Login is forcibly being required                                                          
Index:  0                                                                              
192.241.87.246:3128                                                            
======= Begin Scraping ========                                            
ERROR: Error getting user details for tugba_kocak_88. Please verify that the user exists. 
ERROR: Error getting user details for tugba_kocak_88. Please verify that the user exists. 
ERROR: Error getting user details for sinasangari64. Please verify that the user exists. 
ERROR: Error getting user details for sinasangari64. Please verify that the user exists. 
ERROR: Error getting user details for bircan.bykktk. Please verify that the user exists. 
ERROR: Error getting user details for bircan.bykktk. Please verify that the user exists.  
ERROR: Error getting user details for x.mihribann.x. Please verify that the user exists.  
ERROR: Error getting user details for x.mihribann.x. Please verify that the user exists.  
```

I mean this is what happens

**Comment by Aaronzinhoo** [comment]
Oh yea, the rate limit is not the issue though. I understand how that works but I am more curious about what's occurring with the print statements. I am restarting the after the login is required and changing the proxy but after I restart InstagramScraper it now prints double the statements

**Comment by VasiliPupkin256** [comment]
Aha. So you are calling it in the same process multiple times? I still don't really understand what exactly causing it but there are lines in the beginning of the app.py where it overrides python system stdout file `sys.stdout, sys.stderr = map(...)`.  May be it is caused by this? Do you also import the module multiple times?

**Comment by Aaronzinhoo** [comment]
I only import the class InstagramScraper once initialize it in a loop

**Comment by Aaronzinhoo** [comment]
It is interesting, I just hope this does not mean multiple threads are running and trying to make request because this would cause a rate limit to be reached sooner.

**Comment by VasiliPupkin256** [comment]
It download files in parallel but fetching users and posts sequentially. Instagram only limit calls to graphgl api so this kind of multithreading is tolerated.

**Comment by Aaronzinhoo** [comment]
Ah yes you are right, thanks. It is still weird though this occurs but thanks!

**Comment by VasiliPupkin256** [comment]
Just put a breakpoint on that line where sys.stdout is overwritten and check if it is called twice
