### ISSUE TITLE
password w/ quote 

### ISSUE THREAD

**Issue by TheSaltMaker** [rarcega/instagram-scraper#541]
Imagine having this password `That'sMyPassword` the single quote is a problem for the terminal. 
There is nothing more to add.

**Comment by VasiliPupkin256** [comment]
Which terminal? On linux type That\'sMyPassword

**Comment by TheSaltMaker** [comment]
On powershell

**Comment by TheSaltMaker** [comment]
same problem on linux because it's a single quote

**Comment by VasiliPupkin256** [comment]
Have you ever heard of escaping? \\' works on linux. In powershell use '' https://technet.microsoft.com/en-us/library/hh847740.aspx
This is not an issue of the program

**Comment by TheSaltMaker** [comment]
yeah sure my bad, sorry...
By the way; is it possible to import instagram-scraper to use it from an other code ? ^^'

**Comment by TheSaltMaker** [comment]
well forget, i got an other idea. Thanks for your time and your answers !

**Comment by VasiliPupkin256** [comment]
Yes it is possible but not without problems... I've used the nasty hack to pause output on input in multithreaded environment, hence the issue #539
