### ISSUE TITLE
Question (Not Issue) - PLEASE DELETE

### ISSUE THREAD

**Issue by seanpatel** [rarcega/instagram-scraper#55]
Thank you for reply. You may delete this. I'll keep you posted if I run into any issues in my AI research project

**Comment by rarcega** [comment]
I don't know the rate limits or whether there is a possibility of a ban. The scraper does not provide any defense against either. Proceed with caution and use it responsibly. If you do find out anything, let me know :)

scrapy's documentation provides some [tips on avoiding bans](https://docs.scrapy.org/en/latest/topics/practices.html#avoiding-getting-banned) which you might want to check out. In particular, the section about using proxies may be of interest to you. Hope that helps.
