### ISSUE TITLE
Add option "only_metadata"

### ISSUE THREAD

**Issue by sambokai** [rarcega/instagram-scraper#58]
Hey,

i have made a few changes to the scraper, since my project didn't need the media files themselves:

You can now specify that you only need the json file with the post metadata and don't want the scraper to download all the media files.

Can i issue a pull request?

Greetings,
Sam :)

**Comment by rarcega** [comment]
Although it may not be obvious, you can achieve the same behavior by specifying the `--media_types -t` parameter as something other than `image`, `story`, or `video`:

```bash
# will only download the metadata and not the media
$ instagram-scraper therock -t none --media_metadata 
```

**Comment by sambokai** [comment]
Strange.. I tried that at first but it didn't work. Now it works though. :) 
There should be instructions for it in the docs though. Probably doesn't  seem intuitive to some people

Greetings

**Comment by rarcega** [comment]
Updated the README to make this clear. Thanks.
