### ISSUE TITLE
explore by location not working

### ISSUE THREAD

**Issue by SophMC** [rarcega/instagram-scraper#59]
Hello,

Thank you for developing this and making it freely available! 

My ultimate aim is to gather location info from each post if possible. 

However, I'm not able to get the --location param to work. 
I noticed it is missing from the list of `default_attr`, line 35, in app.py. Is this intentional? 

This line also doesn't work for me `LOCATIONS_URL = BASE_URL + 'explore/locations/{0}/?__a=1'`
doesn't work for me e.g. https://www.instagram.com/explore/locations/{perth}/?__a=1 gives "Sorry, this page isn't available." 

I think this is because each location has an id number associated with it - I'm not sure how you can create a look-up which links the locations to the ids - 
e.g. https://www.instagram.com/explore/locations/251170500/
works the same as: 
https://www.instagram.com/explore/locations/251170500/glendevon-perth-and-kinross-united-kingdom/ 

So it appears the location-id is more important that the location-text.

Cheers,
Sophie

**Comment by rarcega** [comment]
You are correct. The value you must supply with the `--location` argument is the instagram `location-id`. I've updated the README to clarify this. I'm not aware of any service that provides a location-id lookup based off a location name or coordinates besides the [location endpoints](https://www.instagram.com/developer/endpoints/locations/) as provided in the official instagram API.

**Comment by rarcega** [comment]
Added --search-location argument for convenience:

Usage:
```bash
$ instagram-scraper "times square" --search-location
location-id: 3001373, title: Times Square, New York City, subtitle: New York, New York, city: New York, New York, lat: 40.75839, lng: -73.98644
location-id: 3000712, title: W New York - Times Square, subtitle: 1567 Broadway, New York, New York, city: New York, New York, lat: 40.7590349915, lng: -73.985527066
location-id: 253406, title: Sheraton New York Times Square, subtitle: 811 7th Avenue 53rd St, New York, NY, city: New York, NY, lat: 40.76273, lng: -73.98166
location-id: 942903539, title: Hong Kong Times Square, subtitle: 1 Matheson Street, Causeway Bay, Hong Kong, city: Causeway Bay, Hong Kong, lat: 22.2785723548, lng: 114.182350852
location-id: 310113732, title: Pizza Hut, Berjaya Times Square, subtitle: Berjaya Times Square, city: , lat: 3.14114898215, lng: 101.710164327
```

**Comment by SophMC** [comment]
This is really useful, thanks!
