### ISSUE TITLE
url keyerror happening randomly 

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [rarcega/instagram-scraper#6]
`Downloading:   0%|                                                                                                                                         | 0/432 [00:00<?, ?it/s]Traceback (most recent call last):
  File "app.py", line 71, in <module>
    print ('%r generated an exception: %s') % (item['url'], future.exception())
KeyError: 'url'`

**Comment by rarcega** [comment]
Duplicate of #3

**Comment by Rich700000000000** [comment]
Yeah, this keeps happening randomly.

**Comment by rarcega** [comment]
Fixed in f9eef80a9213cee0bfe107aada5797364f1222a4
