### ISSUE TITLE
Would it be possible to do this?

### ISSUE THREAD

**Issue by LewisHolt** [rarcega/instagram-scraper#60]
How would I make it so it would check for the latest image from an account every half an hour and download if there's a new one?

I'd understand -latest would do that but I don't know how to schedule it. 
I suppose a cron job would do it but I'm kinda unsure about this. 

`10 * * * * instagram-scraper instagramname --latest --destination /home/lewis/`

This should be working right? Not seeing any updated images. ;/

**Comment by rarcega** [comment]
This worked for me under macOS. Should be virtually the same on UNIX.

```bash
PATH=/usr/local/bin:/usr/local/sbin:~/bin:/usr/bin:/bin:/usr/sbin:/sbin
MAILTO=""
*/30 * * * * instagram-scraper stradivariuz_  --latest --destination /tmp/instagramname >> /tmp/instagramname.log 2>&1
```
