### ISSUE TITLE
if i scrape more than 10 posts: "typeError: none type object is not iterable"

### ISSUE THREAD

**Issue by pierinpierinpierin** [rarcega/instagram-scraper#65]
hello,

I have this problem with instagram-scraper. 
e.g. "instagram-scraper --tag hello -t none -d D:\instagram -m 100 --media_metadata" I find this error: 

__query_media_gen, media, end_cursor = query_fn(value, end_cursor, csrf_token)
typeError: none type object is not iterable. 

But if I change "-m 10" it works.
why? 

Thank you,
Pier.

**Comment by dberma15** [comment]
I'm having the same problem.

**Comment by rarcega** [comment]
The internal api endpoint for querying hashtags and locations has been removed. As a result, this broke that functionality. There's an alternate endpoint that can be used but it returns less fields as the previous one.

**Comment by bebensiganteng** [comment]
Hi, @rarcega just wondering if you're planning to fix the location? tried it just now, and it didn't work.
