### ISSUE TITLE
Issue with login commands:

### ISSUE THREAD

**Issue by XellossMetallium** [rarcega/instagram-scraper#69]
Hello, I set a job to update my follow list each 15 minutes with instagram-scraper. Until yesterday it worked very well, yet since a couple of days ago the login commands produce this error:

> C:\Users\Administrator\Documents>instagram-scraper --filename Instagram.txt --media_types story --latest --quiet --login_user ****** --login_pass ****** --destination ******* --retain_username
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\instagram-scraper-script.py", line 11, in <module>
    load_entry_point('instagram-scraper==1.4.0', 'console_scripts', 'instagram-scraper')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 655, in main
    scraper.scrape()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 260, in scrape
    self.login()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 71, in login
    if login.status_code == 200 and json.loads(login.text)['authenticated']:
KeyError: 'authenticated'

without the aforementioned commands the job is completed without issue, but obviusly this does not work for stories and private profile.
Since I don't think I changed anything that may have produced the error I reported here.
Thanks.

**Comment by rarcega** [comment]
Scraping private profiles and stories is working fine from my end. Can you verify that you are able to login to instagram normally either through the web or mobile app?

**Comment by XellossMetallium** [comment]
Yes, I can confirm it works. I cannot pinpoint the exact moment the problem started since I run instagram-scraper on a server at home, but fearing a ban I tested, also by changing password, but I can connect like always, from the mobile app (android) and from the same server (chrome).

**Comment by XellossMetallium** [comment]
Small update: I created a different profile (and followed some private profile to adapt to my list). With a different username and password instagram-scraper manages to update correctly, so it seems to actually be related to the main username. But I'm at loss: is it possible to "ban" not an account or an ip, but the "method" instagram-scraper uses to download the content? As I said I can access to my account even from the very same device.

**Comment by rarcega** [comment]
I don't know the exact conditions for triggering it (one of them might be accessing instagram from a different IP), but it may sometimes require you to verify your account to prove you're a human and not a bot. When this happens you may have to enter a verification code sent to your email or prompted by the app to verify the activity.

@XellossMetallium This may have been the issue you were experiencing initially. I added logic to detect this scenario and output an error message with the link to challenge/checkpoint url.

**Comment by XellossMetallium** [comment]
It is a fact that the errors started to occur when I was 700km away from home, so Instagram could have actually see connections from two different locations at the same time. Strange that it asks for confirmation from the older, usual one. 
Anyway, sorry to ask, but do I need something more than running "pip install instagram-scraper --upgrade" to get this particular update? If not, the error I get seems to be the usual.

> 
C:\Users\Administrator>pip install instagram-scraper --upgrade
Requirement already up-to-date: instagram-scraper in c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages
Requirement already up-to-date: requests>=1.0.4 in c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages (from instagram-scraper)
Requirement already up-to-date: tqdm>=3.8.0 in c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages (from instagram-scraper)
Requirement already up-to-date: requests_mock in c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages (from instagram-scraper)
Requirement already up-to-date: nose in c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages (from instagram-scraper)
Requirement already up-to-date: idna<2.6,>=2.5 in c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages (from requests>=1.0.4->instagram-scraper)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages (from requests>=1.0.4->instagram-scraper)
Requirement already up-to-date: certifi>=2017.4.17 in c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages (from requests>=1.0.4->instagram-scraper)
Requirement already up-to-date: urllib3<1.22,>=1.21.1 in c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages (from requests>=1.0.4->instagram-scraper)
Requirement already up-to-date: six in c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages (from requests_mock->instagram-scraper)

C:\Users\Administrator\Documents>instagram-scraper --filename Instagram.txt --media_types image --latest --quiet --login_user XXX --login_pass XXX --destination V:\#ARCHIVIO\USERDATA\Immagini\#PERSONE\#SOCIAL\#INSTAGRAM\Instagram-Scraper\#Foto --retain_username
ERROR: Login failed for xellossmetallium
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\instagram-scraper-script.py", line 11, in <module>
    load_entry_point('instagram-scraper==1.5.0', 'console_scripts', 'instagram-scraper')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 695, in main
    scraper.scrape()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 301, in scrape
    self.login()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 77, in login
    for count, error in enumerate(login_text.get('errors').get('error')):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by rarcega** [comment]
I pushed the fix v1.5.1 to pip just now. Yes, to upgrade you need to run `pip install instagram-scraper --upgrade`.

**Comment by XellossMetallium** [comment]
Just updatetd, the error looks similar. In the logs ("2017-07-02 12:16:46,488 - instagram_scraper.app - ERROR - Login failed for  XXX") or in the command line I don't see the expected url to validate the access.

> ERROR: Login failed for XXX
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\instagram-scraper-script.py", line 11, in <module>
>     load_entry_point('instagram-scraper==1.5.1', 'console_scripts', 'instagram-scraper')()
>   File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 699, in main
>     scraper.scrape()
>   File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 305, in scrape
>     self.login()
>   File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 81, in login
>     for count, error in enumerate(login_text.get('errors').get('error')):
> AttributeError: 'NoneType' object has no attribute 'get'

**Comment by rarcega** [comment]
@XellossMetallium Can you please upgrade to 1.5.2 and try again?

**Comment by XellossMetallium** [comment]
Done, still no luck with the login (by the way ZZZ and YYY are the only two private profiles I added to the list, so at least now the others seems to be correctly checked):

> ERROR: Login failed for XXX
> ERROR: {
>     "authenticated": false,
>     "user": true,
>     "status": "ok"
> }
> ERROR: Failed to get media for ZZZ
> Traceback (most recent call last):
>   File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 428, in media_gen
>     media = self.fetch_media_json(username, max_id=None)
>   File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 455, in fetch_media_json
>     raise ValueError('User {0} is private'.format(username))
> ValueError: User ZZZ is private
> ERROR: Failed to get media for YYY
> Traceback (most recent call last):
>   File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 428, in media_gen
>     media = self.fetch_media_json(username, max_id=None)
>   File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 455, in fetch_media_json
>     raise ValueError('User {0} is private'.format(username))
> ValueError: User YYY is private
>

**Comment by mbrav** [comment]
Had some problems logging in as well. Everything started working once I reset my Insta password and private accounts where scraped flawlessly.

**Comment by XellossMetallium** [comment]
And... yes, you are right! Thank you very much.
@rarcega since for now there is a workaround should I close this issue or do you prefer to investigate further?

**Comment by mbrav** [comment]
@XellossMetallium Glad I helped :)
