### ISSUE TITLE
Inconsistent use of - and _ in command line options

### ISSUE THREAD

**Issue by e-beach** [rarcega/instagram-scraper#82]
In the interest of backwards compatibility, this is probably not something that is going to to be fixed, but if future options are added you should make a choice of which one to use. 

The problem is that the location commands use kebob-case but all other commands use snake_case, e.g., 
`--search-location` ought to be `--search_location` 
and
`--include-location` ought to be `--include_location`.

**Comment by rarcega** [comment]
Agreed. Changed all the arguments to use kebab-case but will still support the older arguments using underscores to preserve backward compatibility.
