### ISSUE TITLE
can I scrape just comments without pictures?

### ISSUE THREAD

**Issue by kzk1221** [rarcega/instagram-scraper#94]
Thanks for all the coding for instagram-scraper, It is quite useful ! 
Question : I sometime just wanna use ''--tags''  ,but then it automatically scrape photos which cause longer time to be done . 
It would be really helpful if you can add   "without pictures '' functon. 
Thanks a lot again.

**Comment by rarcega** [comment]
Pass in `-t none` in the command line arguments.

```
--media-types -t    Specify media types to scrape. Enter as space separated values. 
                    Valid values are image, video, story, or none. Stories require
                    a --login-user and --login-pass to be defined.
```
