### ISSUE TITLE
stories video download is broken

### ISSUE THREAD

**Issue by VasiliPupkin256** [rarcega/instagram-scraper#98]
Just run the
    instagram-scraper karinaelle -t story -u ... -p ...
And you'll have a bunch of zero length mp4

**Comment by PlutoCoder** [comment]
I'm having the same issue. Sometimes I get these empty mp4s, sometimes I don't. Started maybe 48 hours ago.

**Comment by rarcega** [comment]
Fixed in v1.5.4

**Comment by PlutoCoder** [comment]
Confirmed working again in 1.5.4
